#!/usr/bin/env bash
export HISTCONTROL=ignoreboth:erasedups
export HISTFILESIZE=20000
export HISTSIZE=10000
HISTTIMEFORMAT="%d/%m/%y %T "

alias mux="~/digi_backpack/tmux-agent"
Col() { awk '{print $('$(echo $* | sed -e s/-/NF-/g -e 's/ /),$(/g')')}'; }

Repme() {
    cd ~/scratchspace/repos/$1
}

_repos=(`ls ~/scratchspace/repos`)
