#!/usr/bin/env bash

TMUX_VER=tmux2

if [ "$TERM" != "screen" ] && [ -z "$TMUX" ]; then
    # if the auth socket variable is empty, don't do anything
    if [ ! -z "$SSH_AUTH_SOCK" ]; then
        # include USER to protect against shared HOME directories (rare)
        NEWSOCK=$HOME/.agent-sshtmux-$USER.sock
        if [ "$SSH_AUTH_SOCK" != "$NEWSOCK" ]; then
            # test if the auth sock we have is actually working
            # don't link to a dead socket
            if ssh-add -l > /dev/null 2>&1; then
                /bin/ln -sf $SSH_AUTH_SOCK $NEWSOCK
                export SSH_AUTH_SOCK=$NEWSOCK
            fi
        fi
    fi
    TMUX_BIN=$(which $TMUX_VER)
    if [ -n "$TMUX_BIN" ]; then
        exec $TMUX_BIN "$@"
    else
        echo "$0: can't find $TMUX_VER, aborting" >&2
        exit 1
    fi
else
    echo "$0: can't start up tmux inside tmux" >&2
    exit 1
fi
